language: python
python:
  - "3.6"
# setup environment
env:
  - DATABASE_URL=sqlite:///db.sqlite3 SECRET_KEY=secret
# install dependencies
install:
  - pip install -r requirements.txt
# Get sass ready
before_script:
  - gem install sass
# run test scripts
script:
  - flake8
  - python manage.py migrate
  - coverage erase
  - pytest --cov
# run coveralls after successful tests
after_success:
  - coveralls