language: python
python:
  - "3.6"
# setup environment
env:
  - DJANGO_SETTINGS_MODULE='Bnice.test_settings'
# install dependencies
install:
  - pip install -r requirements.txt
# Get sass ready
before_script:
  - gem install sass
# run test scripts
script:
  - python manage.py migrate
  - python manage.py compilestatic
  - coverage erase
  - pytest --cov
# run coveralls after successful tests
after_success:
  - coveralls