release: echo Compiling scss...
release: python manage.py compilestatic
release: echo Compiled scss...
release: echo Collecting static files to Amazon s3...
release: python manage.py collectstatic --noinput
web: gunicorn Bnice.wsgi --log-file -
