#!/usr/bin/env bash

python manage.py migrate --noinput
echo Compiling scss...
python manage.py compilestatic
echo Finished Compiling scss...
echo Collecting static files to Amazon s3...
python manage.py collectstatic --noinput