# Generated by Django 2.0.3 on 2018-04-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180424_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='oopsy',
            name='is_oopsy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='smiley',
            name='is_smiley',
            field=models.BooleanField(default=True),
        ),
    ]
