# Generated by Django 2.0.3 on 2018-04-25 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20180425_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oopsy',
            name='is_oopsy',
        ),
        migrations.RemoveField(
            model_name='smiley',
            name='is_smiley',
        ),
    ]
