# Generated by Django 2.0.3 on 2018-04-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20180426_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oopsy',
            name='earned_on',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='smiley',
            name='earned_on',
            field=models.DateTimeField(),
        ),
    ]
