# Generated by Django 2.0.3 on 2018-05-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20180429_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='oopsy',
            name='claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smiley',
            name='claimed',
            field=models.BooleanField(default=False),
        ),
    ]
