# Generated by Django 2.0.3 on 2018-05-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20180501_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='oopsy',
            name='star_awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smiley',
            name='star_awarded',
            field=models.BooleanField(default=False),
        ),
    ]
