# Generated by Django 2.0.3 on 2018-05-01 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20180501_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oopsy',
            name='points_remaining',
        ),
        migrations.RemoveField(
            model_name='oopsy',
            name='star_awarded',
        ),
    ]
