# Generated by Django 2.1.2 on 2018-12-02 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20181023_2136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oopsy',
            options={'permissions': (('view_oopsy_instance', 'View Oopsy Instance'), ('add_oopsy_instance', 'Add Oopsy Instance'), ('edit_oopsy_instance', 'Edit Oopsy Instance'), ('delete_oopsy_instance', 'Delete Oopsy Instance'))},
        ),
        migrations.AlterModelOptions(
            name='smiley',
            options={'permissions': (('view_smiley_instance', 'View Smiley Instance'), ('add_smiley_instance', 'Add Smiley Instance'), ('edit_smiley_instance', 'Edit Smiley Instance'), ('delete_smiley_instance', 'Delete Smiley Instance'))},
        ),
    ]
