# Generated by Django 2.0.3 on 2018-04-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180419_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='profiles/%Y/%m/%d'),
        ),
    ]
