# Generated by Django 2.0.3 on 2018-04-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180422_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='star_points',
            field=models.PositiveSmallIntegerField(default=15),
        ),
    ]
