# Generated by Django 2.0.3 on 2018-04-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_child_star_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='star_points',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
