# Generated by Django 2.1.2 on 2018-11-10 14:11

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='profiles/%Y/%m/%d', validators=[core.validators.FileValidator]),
        ),
    ]
