# Generated by Django 2.1.2 on 2018-11-11 17:28

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='profiles/%Y/%m/%d', validators=[core.validators.FileValidator(allowed_extensions=['.jpg', '.png', '.gif'], allowed_mimes=['image/jpeg', 'image/png', 'image/gif'], max_size=150, min_size=25)]),
        ),
    ]
