# Generated by Django 2.1.2 on 2018-11-12 22:32

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20181111_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(
                blank=True, upload_to='profiles/%Y/%m/%d',
                validators=[core.validators.ImageValidator(
                    allowed_extensions=['.jpg', '.png', '.gif'],
                    allowed_mimes=['image/jpeg', 'image/png', 'image/gif'],
                    max_height=500,
                    max_size=150,
                    max_width=500,
                    min_height=300,
                    min_size=25,
                    min_width=300)]
            ),
        ),
    ]
