# Generated by Django 2.1.2 on 2018-12-01 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20181112_2232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('view_user_instance', 'View User Instance'), ('add_user_instance', 'Add User Instance'), ('edit_user_instance', 'Edit User Instance'), ('delete_user_instance', 'Delete User Instance'))},
        ),
    ]
