# Generated by Django 2.1.2 on 2018-12-02 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20181201_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'permissions': (('view_child_instance', 'View Child Instance'), ('add_child_instance', 'Add Child Instance'), ('edit_child_instance', 'Edit Child Instance'), ('delete_child_instance', 'Delete Child Instance'))},
        ),
    ]
